const jwt = require("jsonwebtoken");
import { verify } from "crypto";
import { z } from "zod";
const express = require("express");
const app = express();



const schema = z.object({
  name: z.string(),
  password: z.string().min(6),
});

// const value = {
//     name: "arwin",
//     password: "12345",
// }

// const token = jwt.sign(value, "secret");

//this token has been generated by this secret so this can  only be verified by this secret
const emailSchema = zod.string().email();
const passswordschema = zod.string().min(6);
function Verify(username, password) {
    const userName = emailSchema.parse(username);
    const passswordschema = passswordschema.parse(password);
    if (!userName.success || !passswordschema.success) {
        return 0;
    }



    const token = jwt.sign({ username }, "secret");
    
    console.log(token);
}